"""The HTML figures, reached from the report commands that draw them.

``docs/CORRECTIONS.md`` D55. These pages were generated by a standalone script
for their whole life and had **no tests at all** — nothing imported it, so a
change that broke a page was found by opening one in a browser, or not at all.
Moving them into the package is what makes this file possible, and closing that
gap is most of why the move was worth doing.

What is asserted is the contract a self-contained page has to keep: it is one
file with no external reference of any kind, it carries the sections a reader is
told it carries, and a comparison covers every chip it was given. The *contents*
of those sections are pinned where they are computed — ``test_emit`` for the
program, ``test_deploy`` for the sequence listing, ``test_pipeline`` for the
trace — so this does not re-assert them from the far side of an HTML template.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

from bwz.analysis import analyze, machine_model
from bwz.figures import (
    Panel,
    build_matmul,
    build_phases,
    shared_dtype,
    write_animation,
    write_timeline,
)
from bwz.kernels import encoder_layer_kernel, matmul_kernel
from bwz.spec import DeploymentSpec, DType, load_chip

SHAPE = (256, 256, 256)
"""Big enough to have a grid worth drawing, small enough to build instantly."""


def _matmul_panel(chip_id: str, dtype: DType = DType.FP16, **overrides: object) -> Panel:
    m, n, k = SHAPE
    spec = matmul_kernel(m, n, k, a_dtype=dtype, b_dtype=dtype)
    deployment = DeploymentSpec.model_validate(
        {"batch": 1, "input_tokens": 1, "output_tokens": 0, "phase": "prefill", **overrides}
    )
    chip = load_chip(chip_id)
    report = analyze(spec, chip, deployment)
    assert report.feasible, report.infeasibility
    work = build_matmul(chip, spec, deployment, report, steps=64, command="bwz matmul (test)")
    return Panel(chip, dtype, work)


def _encoder_panels(chip_id: str) -> list[Panel]:
    spec = encoder_layer_kernel(dmodel=8, nheads=2, ffn=16, vocab=16, tokens=4)
    deployment = DeploymentSpec.model_validate(
        {"batch": 1, "input_tokens": 4, "output_tokens": 0, "phase": "prefill"}
    )
    chip = load_chip(chip_id)
    report = analyze(spec, chip, deployment)
    assert report.feasible, report.infeasibility
    return [
        Panel(chip, DType.FP16, work)
        for work in build_phases(chip, spec, deployment, report, tokens=4, steps=64)
    ]


# --------------------------------------------------------------- self-contained


EXTERNAL = re.compile(r"""(?:src|href)\s*=\s*["'](?!#)(?!data:)""", re.IGNORECASE)
"""Anything the browser would have to fetch. The whole promise of these pages is
``file://`` with no server, no CDN and no download (``docs/plots/README.md``), so
one stray ``<script src=…>`` breaks the artifact for every offline reader.

Deliberately about *fetches*, not about the string ``http``: both pages carry the
SVG namespace URI ``http://www.w3.org/2000/svg``, which names an XML vocabulary
and is never resolved."""

FETCHES = re.compile(r"\b(?:fetch|XMLHttpRequest|importScripts|WebSocket)\s*\(")
"""Script-side ways to reach the network, which no page here has any use for."""

SCRIPTS = re.compile(r"<script\b[^>]*>(.*?)</script>", re.DOTALL | re.IGNORECASE)


def _is_self_contained(page: str) -> None:
    """No external reference, and no script that could make one.

    ``FETCHES`` runs over the ``<script>`` blocks alone rather than the whole
    page, because the page also *displays* the emitted Python program (D54) — and
    that program has a ``fetch()`` of its own, a staging callback with nothing to
    do with the network. Searching the rendered text for the word would fail on
    source the browser never executes.
    """
    assert not EXTERNAL.search(page), "a self-contained page fetches nothing"
    scripts = SCRIPTS.findall(page)
    assert scripts, "the check below is meaningless if nothing runs"
    for script in scripts:
        assert not FETCHES.search(script), "no script here should reach the network"


@pytest.mark.parametrize("chip_id", ["a100_80gb", "metis_aipu"])
def test_the_timeline_is_one_self_contained_file(tmp_path: Path, chip_id: str) -> None:
    dtype = DType.INT8 if chip_id == "metis_aipu" else DType.FP16
    out = tmp_path / "t.html"
    write_timeline([_matmul_panel(chip_id, dtype)], "bwz matmul (test)", out)

    page = out.read_text(encoding="utf-8")
    assert page.lstrip().lower().startswith("<!doctype html>")
    _is_self_contained(page)


def test_the_animation_is_one_self_contained_file(tmp_path: Path) -> None:
    out = tmp_path / "a.html"
    write_animation(_matmul_panel("a100_80gb"), "bwz matmul (test)", out)

    _is_self_contained(out.read_text(encoding="utf-8"))


# ------------------------------------------------------------------- the sections


def test_the_timeline_carries_the_sections_the_docs_promise(tmp_path: Path) -> None:
    """`docs/plots/README.md` lists what a reader will find on the page.

    A heading that quietly stopped rendering would be found by a reader before it
    was found by a test, which is exactly the state this file exists to end.
    """
    out = tmp_path / "t.html"
    write_timeline([_matmul_panel("a100_80gb")], "bwz matmul (test)", out)
    page = out.read_text(encoding="utf-8")

    assert "Roofline" in page
    assert "How it is deployed on the chip" in page
    assert "The arithmetic, operation by operation" in page
    assert "stationarity" in page, "the banner naming the decomposition (D53)"
    assert "bwz matmul (test)" in page, "the command that regenerates it"


def test_a_tiled_matmul_carries_its_runnable_program(tmp_path: Path) -> None:
    """The deployment section IS the emitted program for a matmul (D54)."""
    out = tmp_path / "t.html"
    write_timeline([_matmul_panel("a100_80gb")], "bwz matmul (test)", out)
    page = out.read_text(encoding="utf-8")

    assert "run it yourself" in page.lower()
    assert "def run_tile(" in page
    assert "matmul-a100_80gb-fp16-os.py" in page, "named, so --emit finds the same file"


def test_a_workload_with_no_tile_grid_falls_back_to_the_sequence_listing(
    tmp_path: Path,
) -> None:
    """fp32 on A100 runs on the CUDA cores, which declare no array geometry.

    There is then no grid to walk and no program to emit, and the page has to
    carry the listing instead of an empty section (D54/D55).
    """
    out = tmp_path / "t.html"
    write_timeline([_matmul_panel("a100_80gb", DType.FP32)], "bwz matmul (test)", out)
    page = out.read_text(encoding="utf-8")

    assert "def run_tile(" not in page
    assert "declares no array geometry" in page


def test_an_encoder_page_draws_every_phase(tmp_path: Path) -> None:
    panels = _encoder_panels("a100_80gb")
    assert len(panels) == 1, "an encoder is prefill only: no cache, no later step"
    out = tmp_path / "t.html"
    write_timeline(panels, "bwz encoder-layer (test)", out)
    assert "The arithmetic, operation by operation" in out.read_text(encoding="utf-8")


# --------------------------------------------------------------------- comparison


def test_a_comparison_page_covers_every_chip(tmp_path: Path) -> None:
    """Both chips on one page, one shared absolute time axis (D29/D37).

    The point of the shared axis is that a bar twice as long took twice as long,
    which only means anything if both machines are actually on the page.
    """
    panels = [_matmul_panel("a100_80gb", DType.INT8), _matmul_panel("metis_aipu", DType.INT8)]
    out = tmp_path / "t.html"
    write_timeline(panels, "bwz matmul (test)", out)
    page = out.read_text(encoding="utf-8")

    assert "NVIDIA A100 SXM4 80GB" in page
    assert "Axelera Metis AIPU" in page
    # One program per chip: the mapping is exactly what differs between the two,
    # so this is the section a comparison must not render once (D54).
    assert page.count("def run_tile(") == 2


def test_a_comparison_refuses_a_precision_a_chip_cannot_run() -> None:
    """Per-chip defaults would silently compare two different workloads (D29).

    Metis has no fp16 datapath, so a shared time axis at fp16 would put a run
    that moved half the bytes beside one that did not. The message names the
    chip and what the two do share (CLAUDE.md #8).
    """
    chips = [load_chip("a100_80gb"), load_chip("metis_aipu")]
    with pytest.raises(SystemExit, match="metis_aipu has no fp16 datapath"):
        shared_dtype(chips, "fp16")
    assert shared_dtype(chips, "int8") is DType.INT8
    assert shared_dtype(chips, None) is DType.INT8, "the best both support"


# ------------------------------------------------------------ figure vs. report


def test_the_figure_is_drawn_from_the_report_it_came_with() -> None:
    """The picture and the table describe one run, not two analyses of one input.

    ``build_matmul`` takes the caller's own ``Report`` and ``DeploymentSpec``
    (D55) precisely so they cannot drift; this pins the consequence — every
    number the drawn trace sums to is the reported one.
    """
    panel = _matmul_panel("a100_80gb")
    work = panel.work
    assert work.phase is not None
    assert work.latency_s == work.phase.ops[0].latency_s
    assert work.flops == work.phase.ops[0].flops
    assert work.trace.reported_latency_s == pytest.approx(work.latency_s, rel=1e-12)


def test_the_drawn_decomposition_is_the_one_the_report_costed() -> None:
    """`--stationarity` reaches the figure, not just the table (D53).

    A page drawing the chip's own dataflow while the numbers above it came from a
    requested one would be the exact failure D53 spent a session removing.
    """
    panel = _matmul_panel("metis_aipu", DType.INT8)
    assert panel.work.machine is not None
    assert panel.work.program is not None
    assert panel.work.program.stationarity is panel.work.machine.stationarity
    assert panel.work.program.grid is not None
    assert panel.work.program.grid.tiles == panel.work.program.predicted["tiles"]


def test_split_k_reaches_the_figure() -> None:
    """A deployment knob the CLI passes has to survive into the drawn page."""
    plain = _matmul_panel("a100_80gb")
    split = _matmul_panel("a100_80gb", split_k=4)
    assert plain.work.program is not None and split.work.program is not None
    assert split.work.program.predicted["tiles"] == 4 * plain.work.program.predicted["tiles"]
    assert machine_model(load_chip("a100_80gb"), DType.FP16).k_partitions == 1
